name: Build & Deploy SyncFusion Backend Image to AWS
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout repository â¬‡ï¸
        uses: actions/checkout@v4

      - name: â˜ï¸ Configure AWS â˜ï¸
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3
      - name: ğŸ§ QEMU ğŸ§
        uses: docker/setup-qemu-action@v2
      - name: ğŸ‹ Amazon ECR  ğŸ‹
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: âš“ï¸ docker buildx setup âš“ï¸
        uses: docker/setup-buildx-action@v2
      - name: ğŸ³ docker build ğŸ³
        uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./Dockerfile
          push: true
          tags: 077004640279.dkr.ecr.ap-southeast-2.amazonaws.com/syncfusion:latest